#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

export NEUTTS_ROOT="${NEUTTS_ROOT:-/home/op/neutts}"
export NEUTTS_VENV="${NEUTTS_VENV:-$NEUTTS_ROOT/.venv}"
export NEUTTS_LLAMA_CPP_LIB_PATH="${NEUTTS_LLAMA_CPP_LIB_PATH:-/home/op/llama.cpp/build-cuda/bin}"
export LLAMA_CPP_LIB_PATH="${LLAMA_CPP_LIB_PATH:-$NEUTTS_LLAMA_CPP_LIB_PATH}"
export NEUTTS_VOICES_DIR="${NEUTTS_VOICES_DIR:-$NEUTTS_ROOT/samples}"
export NEUTTS_HOST="${NEUTTS_HOST:-127.0.0.1}"
export NEUTTS_PORT="${NEUTTS_PORT:-12435}"
export NEUTTS_BACKBONE_DEVICE="${NEUTTS_BACKBONE_DEVICE:-gpu}"
export NEUTTS_CODEC_DEVICE="${NEUTTS_CODEC_DEVICE:-cpu}"
export NEUTTS_CPU_AFFINITY="${NEUTTS_CPU_AFFINITY:-0-3}"
export NEUTTS_LLAMA_THREADS="${NEUTTS_LLAMA_THREADS:-4}"
export NEUTTS_LLAMA_THREADS_BATCH="${NEUTTS_LLAMA_THREADS_BATCH:-4}"
export PYTHONPATH="$REPO_DIR:$NEUTTS_ROOT:${PYTHONPATH:-}"

exec env -u LD_LIBRARY_PATH "$NEUTTS_VENV/bin/python" "$REPO_DIR/server.py"
